# Generated by Django 5.1.4 on 2025-01-06 00:23

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=users.utils.get_profile_picture_upload_path),
        ),
    ]
