# Generated by Django 5.1.4 on 2025-01-06 00:46

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_namedphonenumber_alter_profile_options_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('cellular', 'cellular'), ('landline', 'landline')], max_length=25)),
                ('number', phone_field.models.PhoneField(max_length=31)),
            ],
            options={
                'verbose_name': 'User Phone Number',
                'verbose_name_plural': 'User Phone Numbers',
            },
        ),
        migrations.DeleteModel(
            name='NamedPhoneNumber',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='user_phone_numbers', to='users.phonenumber'),
        ),
    ]
