# Generated by Django 5.1.4 on 2025-01-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_phonenumber_delete_namedphonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone_numbers',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
