# Generated by Django 5.1.4 on 2025-01-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usaddress_contactinfo_mailing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='mailing_address',
        ),
        migrations.DeleteModel(
            name='USAddress',
        ),
    ]
