# Generated by Django 5.1.4 on 2025-01-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customerprofile_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='transaction_history',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
