# Generated by Django 5.1.4 on 2025-01-06 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userdocument_staffprofile_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=50)),
                ('when', models.DateTimeField()),
                ('why', models.TextField()),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_user', to=settings.AUTH_USER_MODEL)),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_events',
            field=models.ManyToManyField(related_name='user_employment_events', to='users.employmentevent'),
        ),
    ]
