# Generated by Django 5.1.4 on 2025-01-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_employmentevent_staffprofile_employment_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='schedule',
            field=models.ManyToManyField(related_name='user_scheduled_times', to='users.scheduledtime'),
        ),
    ]
