# Generated by Django 5.1.4 on 2025-01-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_position_staffprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
