# Generated by Django 5.1.4 on 2025-01-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='user_documents', to='users.userdocument'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_events',
            field=models.ManyToManyField(blank=True, related_name='user_employment_events', to='users.employmentevent'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='user_scheduled_times', to='users.scheduledtime'),
        ),
    ]
