# Generated by Django 5.1.4 on 2025-01-06 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_staffprofile_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
