# Generated by Django 5.1.4 on 2025-01-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_staffprofile_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='supervisor',
        ),
    ]
