# Generated by Django 5.1.4 on 2025-01-06 03:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_staffprofile_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('account_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('bankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.bankaccount')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Deposit Account',
                'verbose_name_plural': 'Deposit Accounts',
            },
            bases=('users.bankaccount',),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='deposit_accounts',
            field=models.ManyToManyField(blank=True, related_name='staff_deposit_accounts', to='users.depositaccount'),
        ),
    ]
