# Generated by Django 5.1.4 on 2025-01-06 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_bankaccount_depositaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True)),
                ('monday_from', models.TimeField()),
                ('monday_to', models.TimeField()),
                ('tuesday', models.BooleanField(default=True)),
                ('tuesday_from', models.TimeField()),
                ('tuesday_to', models.TimeField()),
                ('wednesday', models.BooleanField(default=True)),
                ('wednesday_from', models.TimeField()),
                ('wednesday_to', models.TimeField()),
                ('thursday', models.BooleanField(default=True)),
                ('thursday_from', models.TimeField()),
                ('thursday_to', models.TimeField()),
                ('friday', models.BooleanField(default=True)),
                ('friday_from', models.TimeField()),
                ('friday_to', models.TimeField()),
                ('saturday', models.BooleanField(default=True)),
                ('saturday_from', models.TimeField()),
                ('saturday_to', models.TimeField()),
                ('sunday', models.BooleanField(default=True)),
                ('sunday_from', models.TimeField()),
                ('sunday_to', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
