# Generated by Django 5.1.4 on 2025-01-06 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffavailability_staffprofile_availability_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=25)),
                ('card_brand', models.CharField(choices=[('Visa', 'Visa'), ('MC', 'MasterCard'), ('Amex', 'American Express'), ('Disc', 'Discover')], max_length=25)),
                ('card_number', models.CharField(max_length=19, validators=[django.core.validators.MinLengthValidator(8)])),
                ('expiration_date', models.DateField()),
                ('security_code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3)])),
                ('billing_zip_code', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='payment_methods',
        ),
        migrations.CreateModel(
            name='UserPaymentCard',
            fields=[
                ('paymentcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.paymentcard')),
                ('name', models.CharField(max_length=25)),
                ('primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Card',
                'verbose_name_plural': 'User Payment Cards',
            },
            bases=('users.paymentcard',),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='payment_methods',
            field=models.ManyToManyField(related_name='user_payment_cards', to='users.userpaymentcard'),
        ),
    ]
